service: WISHLY-SPLIT-PAYMENT-LAMBDA
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x

package:
  excludeDevDependencies: true

plugins:
  - serverless-plugin-typescript
  - serverless-offline

functions:
  function1:
    handler: app/index.handler
    events:
      - http:
          path: split-payment
          method: get