service: WISHLY-SPLIT-PAYMENT-LAMBDA
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x

package:
  excludeDevDependencies: true
  exclude:
    - src/test

plugins:
  - serverless-plugin-typescript
  - serverless-offline

functions:
  authorizerFunc:
    handler: src/auth/authorizer.handler

  splitPayment:
    handler: src/app/index.handler
    events:
      - http:
          path: split-payment
          method: get
          authorizer: authorizerFunc
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - Authorization

#    layers:  
# TODO: add layers here at the end