service: WISHLY-SPLIT-PAYMENT-LAMBDA
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  lambdaHashingVersion: 20201221
  deploymentBucket:
    name: serverless-test-deployment

package:
  excludeDevDependencies: true
  exclude:
    - src/test

plugins:
  - serverless-localstack
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-layers
  - serverless-deployment-bucket


custom:
  serverless-layers:
    functions: # optional
      - splitPayment
    dependenciesPath: ./layer/nodejs/package.json
  localstack:
    stages:
      - local
      - host: http://localhost
      - edgePort: 4566

functions:
  authorizerFunc:
    handler: src/app/auth/authorizer.handler

  splitPayment:
    handler: src/app/index.handler
    events:
      - http:
          path: split-payment
          method: get
          #authorizer: authorizerFunc
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - Authorization
    
    